apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-front
spec:
  selector:
    matchLabels:
      app: demo-app-front
  template:
    metadata:
      labels:
        app: demo-app-front
    spec:
      containers:
      - name: demo-app-front
        image: registry.hchome.me/demo/frontend
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: mycr
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-app-front-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-app-front
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-front-svc
spec:
  selector:
    app: demo-app-front
  ports:
  - port: 80
    name: demo-app-front-port
    targetPort: 80
    protocol: TCP
