name: deploy-master-to-k8s

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Login registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Build
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Build
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          tags: "${{ secrets.REGISTRY }}/demo/frontend:latest"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins
        shell: bash
        run: |
          curl -I -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} https://${{ secrets.JENKINS_URL }}/job/deploy-fe/buildWithParameters?token=${{ secrets.DEPLOYMENT_TOKEN }}&APP_NAME=$APP_NAME&NS=$NS

    #   - name: Configure AWS Credentials
    #     uses: aws-actions/configure-aws-credentials@v4
    #     with:
    #       aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
    #       aws-region: "us-west-2"

    #   - name: Checkout
    #     uses: actions/checkout@v4

    #   - name: Setup Build
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: 20

    #   - name: Install dependencies
    #     run: npm install

    #   - name: Build
    #     run: npm run build:prod

    #   - name: Deploy
    #     if: success()
    #     run: aws s3 sync ./dist/game-store-app/browser s3://demo-front-prod
